-- Computes the number of distinct terms generated by a^b for 2 <= a,b <= n 
-- numUniquesUpTo 100 = 9183
import qualified Data.Set as Set

uniquesUpTo n = foldl (\set val -> Set.insert val set) Set.empty 
    [a^b | a <- [2..n], b <- [2..n]]
numUniquesUpTo n = Set.size . uniquesUpTo $ n
